# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: rest.proto for package 'grr'
# Original file comments:
# usage: grpc_tools_ruby_protoc -I ./protos --ruby_out=lib --grpc_out=lib ./protos/rest.proto
#

require 'grpc'
require 'grr/rest_pb'

module Grr
  module RestService
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'grr.RestService'

      rpc :DoRequest, RestRequest, RestResponse
    end

    Stub = Service.rpc_stub_class
  end
end
