# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: rest.proto for package 'xikolo'
# Original file comments:
# usage: grpc_tools_ruby_protoc -I ./protos --ruby_out=lib --grpc_out=lib ./protos/helloworld.proto
#

require 'grpc'
require 'rest_pb'

module Xikolo
  module RestService
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'xikolo.RestService'

      rpc :DoRequest, RestRequest, RestResponse
    end

    Stub = Service.rpc_stub_class
  end
end
